name: Nova core Application

on:
  push:
    branches: [master,
    staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build project
        run: mvn clean install
      - name: Login docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t ikaue573/nova-core-staging.
      - name: Publish image ikaue573/nova-core-staging
        run: docker push
      - name: Run tests on downloaded project
        run: |
            ./mvnw test

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image docker hub
        run: docker pull ikaue573/nova-core-staging:latest
      - name: remove container
        run: docker rm -f nova-core
      - name: Run docker container nova-core
        run: docker run -d -p 8080:8080 -e DATABASE_URL=${{secrets.DATABASE_URL}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} --name nova-core  ikaue573/nova-core-staging